### ISSUE TITLE
Comparison with release-it

### ISSUE THREAD

**Issue by limonte** [fabiospampinato/bump#1]
Some people are using https://github.com/webpro/release-it 

What would be the advantages of using `bump` over `release-it`?

**Comment by fabiospampinato** [comment]
I'm not familiar with release-it, so if somebody who tried them both would like to join the discussion I'd appreciate it.

They overall seem to provide very very similar features (to the point where maybe I could have saved myself some time and just used `release-it` 🤔), maybe some differences could be that:

- release-it has better support for monorepos.
- release-it has built-in support for GitLab.
- release-it is a bit too NPM-centric, bump on the other hand is a bit less opinionated in this regard and requires you to define your own publishing script if you want to publish stuff to NPM or somewhere else (which I guess you could also do with release-it though).
- bump can update arbitrary files.
- the way bump generates changelogs is more customizable.
- release-it relies on an external tool ([`auto-changelog`](https://github.com/CookPete/auto-changelog)) for generating/updating the changelog.

I think the main difference here might be that bump's support for changelogs is built-in, is more customizable, and it doesn't rely on tags (which I think release-it is relying on, but I'm not 100% sure).
