### ISSUE TITLE
Support for tokens within `files` setting

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/bump#10]
I'm building VS Code extension (https://github.com/vfonic/vscode-ada-lightbulb) and would like to use bump to make a release. `vsce package` creates a file with a version number in its name like such: `ada-lightbulb-0.1.2.vsix`. I want to add this file to the github release, but I'm having some issues configuring this properly (I don't think it works):

```json
{
  "release": {
    "enabled": true,
    "github": {
      "enabled": true,
      "open": true,
      "draft": false,
      "prerelease": false,
      "files": ["ada-lightbulb-[version].vsix"]
    }
  },
  "scripts": {
    "prebump": "",
    "postbump": "",
    "prechangelog": "",
    "postchangelog": "",
    "precommit": "",
    "postcommit": "",
    "pretag": "",
    "posttag": "",
    "prerelease": "vsce package",
    "postrelease": ""
  }
}
```

Would this be possible?
How did you solve this?

Thank you!

**Comment by fabiospampinato** [comment]
@vfonic check [cash's](https://github.com/kenwheeler/cash/blob/master/bump.json) `bump.json` or [Notable's](https://github.com/notable/notable/blob/master/bump.json).

It's possible to do, the issue I'm seeing is that you're padding a token to `files`, you can't use tokens there, just plain globs.

I'm not sure adding support for tokens (and what tokens, just what the current version is?) to that config option would be that useful 🤔

**Comment by vfonic** [comment]
Yeah, I checked `cash` already, but as you said, no support for tokens in `files`. I'll check how you're doing this in your VS Code extensions. :)

Thanks!

**Comment by fabiospampinato** [comment]
@vfonic I'm not publishing `.vsix` to github as I don't thing they would be useful.

**Comment by fabiospampinato** [comment]
Support for replacing in arbitrary files got deleted in v3, so closing this.
