### ISSUE TITLE
Commit authors and overall authors

### ISSUE THREAD

**Issue by jletey** [fabiospampinato/bump#12]
I would love to have by each commit the author's name that committed it. As well as having an (optional) section after all of the commits to specify who where all of the people that contributed to the code for the release.

**Comment by fabiospampinato** [comment]
> I would love to have by each commit the author's name that committed it

There's the `[author_name]` token for this already.

I suppose what we actually want under this situation would be author's GitHub username, but I'm not sure how to retrieve that, maybe we would need to make some network requests 🤔 

> As well as having an (optional) section after all of the commits to specify who where all of the people that contributed to the code for the release.

We could add a `[version_authors_names]` token or something, but we'd stumble upon the same aforementioned issue, and I'm not sure how the actual changelog text should be rendered from that, the other templates basically involve just some variable substitutions, this would be more complicated.

**Comment by fabiospampinato** [comment]
Closing as the author of each commit can already be used, and fetching their github handles is out of scope. Listing all authors is out of scope also.
