### ISSUE TITLE
Changelog not having all commit messages

### ISSUE THREAD

**Issue by sebRomeo** [fabiospampinato/bump#13]
Hi, first a big **thanks** for such great lib ! Really love your works !

I don't know why, sometimes, when I `bump` from the cli, it says no changes detected, even if there is new commits since previous version. See this screenshot:

![image](https://user-images.githubusercontent.com/17770809/58809045-782d8980-861b-11e9-81e4-ae7f4eba38ec.png)

Here is my bump.json config:
``` javascript
{
    "version": {
        "initial": "1.0.1",
        "increments": [
            "major",
            "minor",
            "patch"
        ]
    },
    "changelog": {
        "create": true,
        "version": "### v[version]",
        "commit": "[message]",
        "separator": "\n"
    },
    "commit": {
        "enabled": true,
        "message": "Changed version to [version]"
    },
    "scripts": {
        "postchangelog": "",
        "postrelease": "npm publish"
    }
}
```

Also, the postrelease script never seem to have worked.

Thanks a lot :)

**Comment by fabiospampinato** [comment]
We are using [simple-git](https://github.com/steveukx/git-js) under the hood to get the list of commits, and it's more than a bit unreliable. Maybe I should try a newer version 🤔 

Could you perhaps see if that works? (You'll have to update bump's version of `simple-git` in `package.json` to a newer version, `npm i` and then re-try, all this from inside `node_modules/@fabiospampinato/bump`.

Otherwise I would need a repo that reproduces this problem reliably.

> Also, the postrelease script never seem to have worked.

You don't seem to be configuring Bump to make any releases, I guess that's why that script isn't running. Maybe what you want is a `postcommit` script instead.

**Comment by gsaadeh** [comment]
Great work on Bump @fabiospampinato and I am using it now to control the releases. However, we are having the same issue with changelog and i noticed there is https://github.com/CookPete/auto-changelog which can certainly complement the great work that Bump does. Perhaps you can consider using that?

**Comment by fabiospampinato** [comment]
@gsaadeh Switching to another changelog provider would be a breaking (and big) change, I'd much rather fix the underlying issue there.

Can you link to a repo that reproduces the issue?

**Comment by gsaadeh** [comment]
@fabiospampinato I understand your concern but I think the one I suggested offers a lot of flexibility compared to the one built-in. I agree that it's a major and breaking change. Unfortunately the repos I am testing it on are private and not on github. I noticed that it didn't parse many of the old version numbers i had although I am using semantic versioning. I might be able to get you some screenshots although it's not ideal

**Comment by fabiospampinato** [comment]
>  but I think the one I suggested offers a lot of flexibility compared to the one built-in

I think I personally prefer the simplicity of the built-in one 🤷‍♂ 

>  I might be able to get you some screenshots although it's not ideal

Anything that can help me debug the issue would be useful.

**Comment by fabiospampinato** [comment]
Happy to reopen once somebody provides a repro.
