### ISSUE TITLE
Package "unexpected end of file"

### ISSUE THREAD

**Issue by colbyfayock** [fabiospampinato/bump#16]
Hey there,

I'm using bump both locally and on our Jenkins build process and I keep running into an issue where I get an unexpected end of file error on the bump package on version 1.2.2.

![image](https://user-images.githubusercontent.com/1045274/64181617-cf1e4700-ce34-11e9-99d3-d76d23bdca95.png)

Similarly, if you try to download that file manually in your browser, you get a Failed - Network Error: https://registry.yarnpkg.com/@fabiospampinato/bump/-/bump-1.2.2.tgz

![image](https://user-images.githubusercontent.com/1045274/64181737-0f7dc500-ce35-11e9-800c-f16acde07d60.png)

Wondering if anyone else has ran into this before. Unsure if there's an issue with the package or if it's for some reason a Yarn issue.

Using yarn `v1.17.3`

I downgraded to 1.2.1 so far anddd so far so good (knock on wood). Maybe it's a corrupt package in the registry?

Thanks

**Comment by colbyfayock** [comment]
Found this also on the yarn repo: https://github.com/yarnpkg/yarn/issues/4412

May be a content-length header issue? though unsure if it's a package issue.

**Comment by colbyfayock** [comment]
Update: 1.2.1 started to give me the issue as well. Wondering if this is a yarn issue, however, i haven't experienced this on any other packages 🤷‍♂

**Comment by barakd** [comment]
I started experiencing this issue as well, using yarn v1.17.3
usually it's solving itself when running yarn install the second time, although while reasonable on developer machines it very problematic on the CI.
I noticed it's happening only when proxying packages from our private npm registry (hosted on private npm)

**Comment by fabiospampinato** [comment]
I've just tried downloading the package manually as well as installing it via yarn and it works for me, in any case I don't think this is an issue with bump itself, I don't think there's anything I can do to fix it 🤷‍♂
