### ISSUE TITLE
Creating an initial changelog can create duplicate version headings

### ISSUE THREAD

**Issue by dnicolson** [fabiospampinato/bump#17]
When creating a CHANGELOG, if the commit that increased the version number is not the most recent commit, two version headings can be created. Also, the commit that increased the version number is discarded. when creating an initial release it is probably common to update the `package.json` file with more than just the version number.

> ### Version 0.1.0
> 
> -   Update remaining files
>     
> 
> ### Version 0.1.0
> 
> -   Initial commit
>     
> -   Add file

To reproduce:
```
git init
echo '{"version": "0.0.1"}' > package.json
git add .
git commit -m 'Initial commit'
touch file
git add file
git commit -m 'Add file'
echo '{"version": "0.1.0"}' > package.json
echo 'test' > file
git add package.json
git commit -m 'Update package.json'
git add file
git commit -m 'Update remaining files'
bump changelog
```

**Comment by fabiospampinato** [comment]
> two version headings can be created.

I see to headings with the same content in your posted changelog, that sounds like a bug.

> the commit that increased the version number is discarded. 

That is kind of expected actually, I don't think you should bump the version number while at the same time making some changes. This library generates a changelog based on your commits history, the commits that bump version numbers are basically rendered as headings already, I don't think they should be listed explicitly also.

**Comment by dnicolson** [comment]
It looks like if the `isBump` attribute specifically checked for version increases it will resolve the issue.

Also it'd be nice to have the option to create but not commit the changelog with the version bump, even after rebasing some commit messages don't always match up with release notes.

**Comment by fabiospampinato** [comment]
> It looks like if the isBump attribute specifically checked for version increases it will resolve the issue.

PR welcome 👍 	

> Also it'd be nice to have the option to create but not commit the changelog with the version bump, even after rebasing some commit messages don't always match up with release notes.

I'm not sure I'm understanding this correctly, you can only generate the changelog by running `bump changelog`, and you can disable the commit step by setting `commit.enabled: false` in the configuration file. Is that what you want? 🤔

**Comment by dnicolson** [comment]
Would `commit.enabled: false` also disable commits for actual version bumps though?

**Comment by fabiospampinato** [comment]
@dnicolson Yes. I'm not sure I understand exactly what you need if this doesn't work for you 🤔
