### ISSUE TITLE
Caporal.js dependency with `git://`

### ISSUE THREAD

**Issue by giupo** [fabiospampinato/bump#18]
Being behind a corporate proxy, the `git://` protocol specified in package.json for Caporal.js is blocked. is switching to `https://` a viable option?

**Comment by fabiospampinato** [comment]
Sorry I have no interest in this, I'm not even sure if using `https` would work, get your company's proxy fixed instead.

**Comment by FuggyD** [comment]
to use https you could change your git config locally:
`git config --global url."https://github.com/".insteadOf git@github.com`
