### ISSUE TITLE
[version] Unsupported repository

### ISSUE THREAD

**Issue by ostrolucky** [fabiospampinato/bump#2]
```
➜  stdinho git:(master) ✗ git tag
0.1
0.2
0.2.1
0.2.3
0.2.4
v0.2.2
➜  stdinho git:(master) ✗ bump
[version] Unsupported repository
```

project: https://github.com/ostrolucky/stdinho

**Comment by amallia** [comment]
Same issue

**Comment by fabiospampinato** [comment]
@ostrolucky there doesn't look like there's actually a problem with bump, it just found nowhere what the current version is, so it tells you that you can't bump it. But you can configure it manually to update arbitrary files, for instance this might be a valid `bump.json` configuration file:

```json
{
  "files": {
    "README.md": [
      ["^# stdinho ?v?(.*)", "# stdinho v[version]"]
    ]
  }
}
```

Is there a kind of standard place where the version of the project should be located in PHP projects?

**Comment by fabiospampinato** [comment]
@amallia same for your repo, something like this for example will work:

```
{
  "files": {
    "README.md": [
      ["^# PISA: Performant Indexes and Search for Academia ?v?(.*)", "# PISA: Performant Indexes and Search for Academia v[version]"]
    ]
  }
}
```

**Comment by amallia** [comment]
> @amallia same for your repo, something like this for example will work:
> 
> ```
> {
>   "files": {
>     "README.md": [
>       ["^# PISA: Performant Indexes and Search for Academia ?v?(.*)", "# PISA: Performant Indexes and Search for Academia v[version]"]
>     ]
>   }
> }
> ```

Thanks.

Can you clarify why it does not automatically perform `tag` with the above configuration?

**Comment by fabiospampinato** [comment]
Maybe we could infer the current version from tags 🤔 let's track this [here](https://github.com/fabiospampinato/bump/issues/7).

**Comment by simontaylor-trilogy** [comment]
For others which get unsupported repository. You need to ensure you have a line which matches the regex including the base version number in the files statement.

**Comment by FuggyD** [comment]
additional: when incorrect json format is used in bump.json the error "Unsupported Repository" also appears
