### ISSUE TITLE
Group commits

### ISSUE THREAD

**Issue by gazorby** [fabiospampinato/bump#20]
First, thanks @fabiospampinato, i love bump!

I started using it recently, and i really like the level of customization while being easy to use.
The only thing missing for me currently would be an option to group changelogs by category, so we would have something like this :

    Bug fixes :
    - fix: 1
    - fix(scope): 2
    - fix(scope): 3

    Features :
    - feat(scope): 1
    - feat: 2
    - feat: 3
Configurable regexes could be used to look for categories, then bump would group and sort them accordingly for the current version. For example, here are the parameters that would be needed to group change logs like the result above :

    {
      "changelog": {
        "categories": [
          ["^feat(\\(.*\\))?:.*$", "Features"],
          ["^fix(\\(.*\\))?:.*$", "Bug fixes"]
        ]
      },
    }

**Comment by fabiospampinato** [comment]
IMHO this can't be done reliably automatically, unless commits messages are constrained in some way, and I'm not interested in implementing that kind of constrain.
