### ISSUE TITLE
bump version in subfolder

### ISSUE THREAD

**Issue by FuggyD** [fabiospampinato/bump#21]
Hi, we've got an Java + React project with this structure:

/src => java files
/typescript => there is the package.json

is there any way to update version in package.json in subfolder?
I tried it with this bump.json on top of project files:

```json
{
  "version": {
    "enabled": true,
    "increments": ["major", "minor", "patch", "premajor", "preminor", "prepatch", "prerelease", "custom"]
  },
  "files": {
    "./typescript/package.json": ["'(?:\"VERSION\": \")(.*)(?:\")'", "[version]", "gi"]
  },
  "changelog": {
    "enabled": true,
    "create": true,
    "open": false,
    "file": "CHANGELOG2.md",
    "version": "### Version [version]",
    "commit": "- [message]",
    "separator": "\n"
  },
  "commit": {
    "enabled": true,
    "message": "Bumped version to [version]"
  },
  "tag": {
    "enabled": true,
    "name": "[version]"
  }
}
```

on every test it could not find the version from the package.json and will set 0.0.0 as tag, which runs on error:
`Error: Command failed: git tag 0.0.0`

**Comment by fabiospampinato** [comment]
It's possible to bump the version in any file, I think your approach is mostly correct but I guess the regex you wrote doesn't match the version field.

Try something like this:

```json
{
'./typescript/package.json': ['"version":\\s*"([^"]*?)"', '"version": "[version]"', "mi"],
}
```

**Comment by FuggyD** [comment]
ok, you're right, the subfolder is not the problem; the regex doesn't fit.
your solution isn't correct json format and causes "Unsupported Repository" error (due to wrong json)

**Comment by FuggyD** [comment]
I think I got it:
`    "./typescript/package.json": ["\"version\":\\s*\"([^\"]*?)\"", "\"version\": \"[version]\"", "mi"]`

**Comment by fabiospampinato** [comment]
👍
