### ISSUE TITLE
Support for version 2 of npm's lockfile

### ISSUE THREAD

**Issue by dnicolson** [fabiospampinato/bump#29]
Starting with version 2 of the lockfile, npm is saving the version twice in the package-lock.json but bump only updates the first instance. 

Using the [npm](https://github.com/npm/cli) project as example, [version 2](https://github.com/npm/cli/blob/53ed7e5205a3f4d5d33828ff9dc11c093f482f7b/package-lock.json) of the lockfile introduced an empty package at the top of the file with the same version metadata. The same applies for [version 3 ](https://github.com/npm/cli/blob/5447810c8f2ca99e5099c7477424266d0a62b342/package-lock.json)of the lockfile.

**Comment by fabiospampinato** [comment]
Should be fixed in v3.
