### ISSUE TITLE
bump changelog - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ostrolucky** [fabiospampinato/bump#3]
```
➜  stdinho git:(master) ✗ bump changelog   
Updating the changelog...

Cannot read property 'length' of undefined
```

**Comment by JayaKrishnaNamburu** [comment]
Hi @ostrolucky  can you provide few more details on how to replicate this, that would be so helpful :smile:

**Comment by ostrolucky** [comment]
```
➜  git clone git@github.com:ostrolucky/stdinho.git
Cloning into 'stdinho'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 992 (delta 39), reused 58 (delta 19), pack-reused 910
Receiving objects: 100% (992/992), 479.42 KiB | 958.00 KiB/s, done.
Resolving deltas: 100% (357/357), done.
➜  cd stdinho
➜  bump changelog
Updating the changelog...
? No changelog found, do you want to create it? Yes

Cannot read property 'length' of undefined
```

**Comment by JayaKrishnaNamburu** [comment]
> ```
> ➜  git clone git@github.com:ostrolucky/stdinho.git
> Cloning into 'stdinho'...
> remote: Enumerating objects: 82, done.
> remote: Counting objects: 100% (82/82), done.
> remote: Compressing objects: 100% (59/59), done.
> remote: Total 992 (delta 39), reused 58 (delta 19), pack-reused 910
> Receiving objects: 100% (992/992), 479.42 KiB | 958.00 KiB/s, done.
> Resolving deltas: 100% (357/357), done.
> ➜  cd stdinho
> ➜  bump changelog
> Updating the changelog...
> ? No changelog found, do you want to create it? Yes
> 
> Cannot read property 'length' of undefined
> ```

will look into this :smile:

**Comment by fabiospampinato** [comment]
@ostrolucky your project is not supported, this is mostly made for node stuff, where the library knows how to infer the version of the library. You should keep an eye on this issue: https://github.com/fabiospampinato/bump/issues/7, or potentially I think you could still use bump if you configured it to update the version in some file it can find, currently the only way to infer the version is by traversing the commits history, which is not supported currently.
