### ISSUE TITLE
Support for macOS Ventura

### ISSUE THREAD

**Issue by dnicolson** [fabiospampinato/bump#30]
Running bump on macOS Ventura results in the following error:
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

This is due to `@octokit/rest` being pinned at version 16.25.0 and versions of `os-name` earlier than version 4.0.0 will throw that error if the version of macOS is unknown (macOS 13 was added to `macos-release` in version 3.1.0).

```
npm ls macos-release
├─┬ @octokit/rest@16.25.0
│ └─┬ universal-user-agent@2.1.0
│   └─┬ os-name@3.1.0
│     └── macos-release@2.5.0
```

**Comment by joshmeads** [comment]
@dnicolson do you know if this is still an issue? My team is running Ventura with no issues currently (via Yarn 3).

**Comment by dnicolson** [comment]
Thanks for reporting, version 2.5.1 of `macos-release` resolves the issue.
