### ISSUE TITLE
Version 1.2.2 npm broken

### ISSUE THREAD

**Issue by tylerclark** [fabiospampinato/bump#33]
Not sure what happened but 20 hours ago the following command no longer works:
`npm install @fabiospampinato/bump@1.2.2 -g`

Error:
```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/fabiospampinato/Caporal.js.git
npm ERR! Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

**Comment by fabiospampinato** [comment]
Versions below v3 are dead and not supported anymore.

**Comment by tylerclark** [comment]
Wow. Way to kill our pipeline without notice. npm packages are versioned for a reason.

**Comment by fabiospampinato** [comment]
Sorry about that, I didn't realize that deleting my fork of Caporal would have much of an impact. Just upgrading to v3 should be better anyway, it's faster, it has no third-party dependencies whatsoever. If you find issues with that then I'm happy to help.

**Comment by tylerclark** [comment]
v3 doesn't even work.

```
$ bump patch
✖ Version bump failed

Error: Unable to update version in package-lock.json file
```

**Comment by fabiospampinato** [comment]
Can you post a little repro? Mainly seeing the `package.json` and `package-lock.json` files for that repo should uncover the issue.
