### ISSUE TITLE
`bump changelog` - Invalid option.

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/bump#9]
I just installed bump and wanted to give it a test run.

I added this global config (`~/.bump/json`):

```json
{
  "force": false,
  "silent": false,
  "version": {
    "enabled": true,
    "initial": "0.1.0",
    "increments": ["major", "minor", "patch"]
  },
  "changelog": {
    "enabled": true,
    "create": false,
    "open": false,
    "file": "CHANGELOG.md",
    "version": "## [version] ([version_date])",
    "commit": "- [message]",
    "separator": "\n"
  },
  "commit": {
    "enabled": true,
    "message": "[version]"
  },
  "tag": {
    "enabled": true,
    "name": "[version]"
  },
  "release": {
    "enabled": false
  },
  "tokens": {
    "date": {
      "format": "YYYY-MM-DD"
    },
    "version_date": {
      "format": "YYYY-MM-DD"
    }
  }
}
```

And then I ran:

`bump changelog` from the root of my project:

```sh
$ bump changelog
Invalid option. Choose between major,minor,patch,pre,set,current,file.
```

I then copied over the `.bump.json` as both `./bump.json` and `./.bump.json`, but none of the two worked.

Any ideas?

EDIT: I stripped down most of the config from `bump.json` file and even removed the file (both local and global) completely. `bump changelog` still fails with the same error message.

**Comment by vfonic** [comment]
More info:

```
$ bump current
Unable to find a file with the gem version
```


Ohhhhh, the issue is due to name collision with another similar library, but written as a ruby gem: https://github.com/gregorym/bump

I guess there's not much to do here...apart from considering renaming the default cli command. :)
Feel free to close this issue after reading it.

Thanks!

**Comment by fabiospampinato** [comment]
Also I think you might have got the location/name of the bump.json file wrong.

**Comment by vfonic** [comment]
The location seems fine.

I got it to work like this:

// https://github.com/vfonic/vscode-ada-lightbulb/blob/master/bump.json
```json
{
  "release": {
    "enabled": true,
    "github": {
      "enabled": true,
      "open": true,
      "draft": false,
      "prerelease": false,
      "files": ["ada-lightbulb-*.vsix"]
    }
  },
  "scripts": {
    "prebump": "",
    "postbump": "",
    "prechangelog": "",
    "postchangelog": "",
    "precommit": "",
    "postcommit": "",
    "pretag": "",
    "posttag": "",
    "prerelease": "vsce package",
    "postrelease": "vsce publish && rm ada-lightbulb-*.vsix"
  }
}
```

Works just fine. I don't need vsix files after releasing (I could add installation step in there)
